name: appologi_es
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.2.0
  dbcrypt: ^2.0.0
  ecdsa: ^0.0.4
  elliptic: ^0.3.8
  hex: ^0.2.0
  image: ^3.2.2
  jaguar_jwt: ^3.0.0
  lzma: ^1.0.1
  tuple: ^2.0.1

dev_dependencies:
  test: ^1.16.5
  conduit_test: ^3.2.0
